CREATE TABLE IF NOT EXISTS visits (
    id              VARCHAR(36)  PRIMARY KEY,
    patient_id      VARCHAR(36)  NOT NULL,
    entry_type      VARCHAR(20)  NOT NULL DEFAULT 'new',
    status          VARCHAR(50)  NOT NULL DEFAULT 'loading_context',
    machine_state   VARCHAR(50)  NOT NULL DEFAULT 'loadingContext',
    started_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ended_at        TIMESTAMP    NULL,
    timeout_at      TIMESTAMP    NULL,
    paused_at       TIMESTAMP    NULL,
    ask_round       INT          NOT NULL DEFAULT 0,
    ask_round_limit INT          NOT NULL DEFAULT 20,
    lab_round       INT          NOT NULL DEFAULT 0,
    lab_round_limit INT          NOT NULL DEFAULT 10,
    parent_session_id VARCHAR(36) NULL,
    terminal_reason VARCHAR(50)  NULL,
    active_card_id  VARCHAR(36)  NULL,
    timer_paused    TINYINT(1)   NOT NULL DEFAULT 0,
    summary         JSON         NOT NULL DEFAULT ('{}'),
    FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE,
    INDEX idx_visits_patient_id (patient_id),
    INDEX idx_visits_status (status),
    INDEX idx_visits_started_at (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
