repos:
  - repo: local
    hooks:
      - id: go-test-cover
        name: Go Test Cover (>=80%)
        entry: bash -c 'go test -race -cover -short ./...'
        language: system
        pass_filenames: false
        types: [go]

      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run ./...
        language: system
        pass_filenames: false
        types: [go]
