package workbench

import (
	"context"
	"fmt"
	"time"

	"github.com/neuhis/software-practice-backend/internal/adapter"
	"github.com/neuhis/software-practice-backend/internal/model"
)

// SubmitLabDecisionInput is the input for submitting a lab decision.
type SubmitLabDecisionInput struct {
	SessionID string
	CardID    string
	Decision  string // accepted, skipped, vetoed
}

// SubmitLabDecision processes a patient's lab decision.
func (s *Service) SubmitLabDecision(ctx context.Context, input SubmitLabDecisionInput) (*model.FlowActionResult, error) {
	session, err := s.visitRepo.FindByID(ctx, input.SessionID)
	if err != nil {
		return nil, err
	}

	card, err := s.flowCardRepo.FindByID(ctx, input.CardID)
	if err != nil {
		return nil, err
	}

	result := &model.FlowActionResult{
		SessionID: input.SessionID,
	}

	now := time.Now()
	card.HandledAt = &now

	switch input.Decision {
	case "accepted":
		card.Status = string(model.FlowCardStatusAccepted)
		_ = s.flowCardRepo.Update(ctx, card)

		// Create payment card for lab tests
		items := []model.PaymentLineItem{
			{Name: "血常规", Amount: 50.0, Quantity: 1},
		}
		paymentCard := adapter.BuildPaymentCard(input.SessionID, "lab", items, 50.0)
		if err := s.flowCardRepo.Create(ctx, paymentCard); err != nil {
			return nil, fmt.Errorf("create payment card: %w", err)
		}

		// Update state to labPayment
		_ = string(model.VisitMachineStateLabPayment) // transition recorded
		status := string(model.VisitStatusBlocked)
		cardID := paymentCard.ID
		session.Status = status
		session.ActiveCardID = &cardID
		_ = s.visitRepo.Update(ctx, session)

		result.Status = status
		result.ActiveCardID = &cardID
		result.Card = paymentCard
		result.Message = "检验已确认，请完成缴费"

		// Create timeline items
		decisionTL := adapter.BuildSystemEventTimelineItem(input.SessionID,
			string(model.SystemEventTypeLabResultReceived),
			"检验决定",
			fmt.Sprintf("患者选择：%s", input.Decision),
		)
		s.timelineRepo.Append(ctx, &decisionTL)

		cardTL := adapter.BuildFlowCardTimelineItem(input.SessionID, paymentCard)
		s.timelineRepo.Append(ctx, &cardTL)
		result.TimelineItems = []model.TimelineItem{decisionTL, cardTL}

	case "skipped":
		card.Status = string(model.FlowCardStatusSkipped)
		_ = s.flowCardRepo.Update(ctx, card)

		// Go straight to diagnosis
		_ = string(model.VisitMachineStateDiagnosis) // transition recorded
		status := string(model.VisitStatusDiagnosis)
		session.Status = status
		session.ActiveCardID = nil
		_ = s.visitRepo.Update(ctx, session)

		result.Status = status
		result.Message = "已跳过检验，进入诊断阶段"

		skipTL := adapter.BuildSystemEventTimelineItem(input.SessionID,
			"lab_skipped",
			"跳过检验",
			"患者选择不进行检验",
		)
		s.timelineRepo.Append(ctx, &skipTL)
		result.TimelineItems = []model.TimelineItem{skipTL}

	case "vetoed":
		card.Status = string(model.FlowCardStatusVetoed)
		_ = s.flowCardRepo.Update(ctx, card)

		// Return to chatting
		_ = string(model.VisitMachineStateChatting) // transition recorded
		status := string(model.VisitStatusChatting)
		session.Status = status
		session.ActiveCardID = nil
		_ = s.visitRepo.Update(ctx, session)

		result.Status = status
		result.Message = "已暂不决定，回到问诊"

		vetoTL := adapter.BuildSystemEventTimelineItem(input.SessionID,
			"lab_vetoed",
			"暂不决定",
			"患者选择暂不决定是否检验",
		)
		s.timelineRepo.Append(ctx, &vetoTL)
		result.TimelineItems = []model.TimelineItem{vetoTL}

	default:
		return nil, fmt.Errorf("invalid lab decision: %s", input.Decision)
	}

	return result, nil
}

// SubmitLabResultsInput is the input for submitting lab results.
type SubmitLabResultsInput struct {
	SessionID string
	Results   []struct {
		Item  string
		Value string
	}
}

// SubmitLabResults processes lab test results (typically called internally after payment).
func (s *Service) SubmitLabResults(ctx context.Context, input SubmitLabResultsInput) error {
	// Create lab_execution card with results
	card := &model.FlowCard{
		ID:              "", // generated by DB
		SessionID:       input.SessionID,
		Kind:            string(model.FlowCardKindLabExecution),
		Status:          string(model.FlowCardStatusCompleted),
		Blocking:        false,
		Title:           "检验结果",
		CreatedAt:       time.Now(),
		ExecutionStatus: string(model.LabExecutionStatusResultReady),
	}

	summary := "检验完成"
	if len(input.Results) > 0 {
		summary = fmt.Sprintf("%s: %s", input.Results[0].Item, input.Results[0].Value)
	}
	card.ResultSummary = &summary

	// Create result timeline item
	resultTL := adapter.BuildSystemEventTimelineItem(input.SessionID,
		string(model.SystemEventTypeLabResultReceived),
		"检验结果已出",
		summary,
	)

	return s.timelineRepo.Append(ctx, &resultTL)
}
